### ISSUE TITLE
Running Bypass UacMethodNetOle32 broke WMI and spawn elevated shells

### ISSUE THREAD

**Issue by H3LL0WORLD** [FuzzySecurity/PowerShell-Suite#3]
I found that after running the UacMethodNetOle32 Bypass, WMI doesn't work anymore.

![error](https://cloud.githubusercontent.com/assets/19286453/22276969/bb6515a6-e285-11e6-9a7b-c871da0082e8.png)
...and if I try to run procexp.exe, procmon.exe, etc. instead of running it properly it spawns me a powershell console.
![error](https://cloud.githubusercontent.com/assets/19286453/22277302/80d94f30-e288-11e6-9671-8b798628464e.gif)

**Comment by FuzzySecurity** [comment]
Hey, I know why this happens. I suspect you closed the script prematurely and it did not remove Yamabiko. As I mention in my blogpost, this dll is loaded by pretty much 30% of everything you run. To correct the issue go to:

C:\Windows\Microsoft.NET\Framework[64]\

One of the folders in there will have "ole32.dll", delete it. After that everything will go back to normal.

**Comment by H3LL0WORLD** [comment]
Well, I tried that but it didn't work.
What I did was restore the PC using a system restore point.
Thanks :)

**Comment by FuzzySecurity** [comment]
Pretty sure that was the issue, which is why I highlighted in my post it could be used as a persistence mechanism (provided you make a transparent proxy dll). Anyway, closing this.
